# -*- coding: utf-8 -*-
"""VisionTransformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CH4007Pbavs_iThiiNUTFhwGXbrV4FD
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import transforms
from torchvision.datasets import CIFAR10, CIFAR100
from torchvision.models import resnet18
from torch.utils.data import DataLoader, Subset
import os
from google.colab import drive
from torch.utils.tensorboard import SummaryWriter
import numpy as np
from tqdm import tqdm

#Initialize global variables
drive.mount('/content/drive')
checkpoint_dir = '/content/drive/MyDrive/checkpoints'
os.makedirs(checkpoint_dir, exist_ok=True)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

writer_pretrain = SummaryWriter(log_dir="runs/pretraining")
writer_finetune = SummaryWriter(log_dir="runs/finetuning")
writer_testing = SummaryWriter(log_dir="runs/testing")

transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize images to 224x224 for ViT
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.4914, 0.4822, 0.4465],
        std=[0.2023, 0.1994, 0.2010])
])

transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
])

transform_test = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
])

class PatchEmbedding(nn.Module):
    def __init__(self, img_size, patch_size, in_channels, embed_dim):
        super(PatchEmbedding, self).__init__()
        self.img_size = img_size
        self.patch_size = patch_size
        self.num_patches = (img_size // patch_size) ** 2
        self.projection = nn.Conv2d(in_channels, embed_dim, kernel_size=patch_size, stride=patch_size)

    def forward(self, x):
        # x shape: [batch_size, in_channels, img_size, img_size]
        x = self.projection(x)  # [batch_size, embed_dim, num_patches ** 0.5, num_patches ** 0.5]
        x = x.flatten(2)  # Flatten the height and width into a single dimension
        x = x.transpose(1, 2)  # [batch_size, num_patches, embed_dim]
        return x

class TransformerEncoderLayer(nn.Module):
    def __init__(self, embed_dim, num_heads, mlp_dim, dropout=0.2):  # Increased dropout to 0.2
        super(TransformerEncoderLayer, self).__init__()
        self.attention = nn.MultiheadAttention(embed_dim, num_heads, dropout=dropout)
        self.mlp = nn.Sequential(
            nn.Linear(embed_dim, mlp_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(mlp_dim, embed_dim),
            nn.Dropout(dropout)
        )
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)

    def forward(self, x):
        # Self-attention layer
        attn_output, _ = self.attention(x, x, x)
        x = x + attn_output  # Add & Norm
        x = self.norm1(x)

        # Feed-forward layer
        mlp_output = self.mlp(x)
        x = x + mlp_output  # Add & Norm
        x = self.norm2(x)
        return x

class VisionTransformer(nn.Module):
    def __init__(self, img_size=224, patch_size=16, in_channels=3, num_classes=10, embed_dim=768, depth=12, num_heads=12, mlp_dim=3072, dropout=0.2):  # Increased dropout to 0.2
        super(VisionTransformer, self).__init__()
        self.patch_embed = PatchEmbedding(img_size, patch_size, in_channels, embed_dim)
        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.pos_embed = nn.Parameter(torch.randn(1, self.patch_embed.num_patches + 1, embed_dim))
        self.dropout = nn.Dropout(dropout)

        self.encoder_layers = nn.ModuleList([
            TransformerEncoderLayer(embed_dim, num_heads, mlp_dim, dropout)
            for _ in range(depth)
        ])

        self.norm = nn.LayerNorm(embed_dim)
        self.classifier = nn.Linear(embed_dim, num_classes)

    def forward(self, x):
        # Create patch embeddings
        x = self.patch_embed(x)

        # Concatenate class token
        batch_size = x.shape[0]
        cls_tokens = self.cls_token.expand(batch_size, -1, -1)
        x = torch.cat((cls_tokens, x), dim=1)  # [batch_size, num_patches + 1, embed_dim]

        # Add positional encoding
        x = x + self.pos_embed
        x = self.dropout(x)

        # Pass through transformer encoder layers
        for layer in self.encoder_layers:
            x = layer(x)

        # Classification head
        x = self.norm(x)
        cls_token_final = x[:, 0]  # Take the final state of the class token
        logits = self.classifier(cls_token_final)

        return logits

def train(model, train_loader, optimizer, criterion, device):
    model.train()
    running_loss = 0.0
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    return running_loss / len(train_loader)

def evaluate(model, train_loader, criterion, device):
    model.eval()
    correct = 0
    total = 0
    running_loss = 0.0
    with torch.no_grad():
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            correct += (predicted == labels).sum().item()
            total += labels.size(0)
    accuracy = 100 * correct / total
    return running_loss / len(train_loader), accuracy

def train_with_early_stopping(model, train_loader, val_loader, optimizer, criterion, device, patience=3):
    model.train()
    best_val_loss = np.inf
    epochs_without_improvement = 0

    for epoch in range(50):
        train_loss = train(model, train_loader, optimizer, criterion, device)

        val_loss, val_accuracy = evaluate(model, val_loader, criterion, device)
        print(f"Epoch {epoch+1}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}, Val Accuracy: {val_accuracy:.2f}%")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            epochs_without_improvement = 0
            save_checkpoint(model, optimizer, epoch, f"{checkpoint_dir}/best_model.pth")
        else:
            epochs_without_improvement += 1
            if epochs_without_improvement >= patience:
                print("Early stopping triggered!")
                break

# Save/load checkpoints
def save_checkpoint(model, optimizer, epoch, path):
    checkpoint = {
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict()
    }
    torch.save(checkpoint, path)

def load_checkpoint(model, optimizer, path):
    checkpoint = torch.load(path, weights_only=True)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    return model, optimizer, start_epoch

def load_checkpoint_ignore_classifier(model, optimizer, path):
    checkpoint = torch.load(path, weights_only=True)
    state_dict = checkpoint['model_state_dict']

    state_dict.pop('classifier.weight', None)
    state_dict.pop('classifier.bias', None)

    model.load_state_dict(state_dict, strict=False)

    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

    start_epoch = checkpoint['epoch'] + 1
    return model, optimizer, start_epoch

#Load and preprocess CIFAR-100 dataset
def load_cifar100_subset(subset_size):
    # Load the CIFAR-100 dataset
    train_dataset = CIFAR100(root='./data', train=True, download=True, transform=transform)

    # Select a subset of the dataset
    subset_indices = torch.randperm(len(train_dataset))[:subset_size]
    train_subset = Subset(train_dataset, subset_indices)

    # Return a DataLoader for the subset
    return DataLoader(train_subset, batch_size=128, shuffle=True, num_workers=2)

# Pretrain on CIFAR-100
def pretrain_on_cifar100(model, train_loader, subset_size, optimizer, criterion, device):
    train_loader = load_cifar100_subset(subset_size)
    print(f"Pretraining on {subset_size} samples of CIFAR-100")

    for epoch in range(100):  # Set a fixed number of epochs for pretraining
        train_loss = train(model, train_loader, optimizer, criterion, device)
        writer_pretrain.add_scalar(f"Loss/CIFAR100_Subset_{subset_size}", train_loss, epoch)
        print(f"Epoch {epoch+1}, Loss: {train_loss:.4f}")
        # Optionally save a checkpoint after pretraining
        save_checkpoint(model, optimizer, epoch, f"{checkpoint_dir}/cifar100/subset_{subset_size}/vit_cifar100_subset_{subset_size}_epoch_{epoch+1}.pth")

#Fine-tune the pretrained model on CIFAR-10
def fine_tune_on_cifar10(model, train_loader, optimizer, criterion, device, subset_size, num_epochs=10):
    for epoch in range(num_epochs):
        train_loss = train(model, train_loader, optimizer, criterion, device)
        writer_finetune.add_scalar(f"Loss/CIFAR10_Subset_{subset_size}", train_loss, epoch)
        print(f"Epoch {epoch+1}, Loss: {train_loss:.4f}")
        # Save checkpoint after fine-tuning
        save_checkpoint(model, optimizer, epoch, f"{checkpoint_dir}/cifar10/subset_{subset_size}/vit_cifar10_subset_{subset_size}_epoch_{epoch+1}.pth")

# Pretrain on CIFAR-100 with 100 classes
pretrain_model = VisionTransformer(img_size=224, patch_size=16, in_channels=3, num_classes=100, embed_dim=256, depth=3, num_heads=8, mlp_dim=1024).to(device)
pretrain_optimizer = optim.Adam(pretrain_model.parameters(), lr=1e-4, weight_decay=1e-5)
criterion = nn.CrossEntropyLoss()

# Pretrain the model on CIFAR-100 subset
for subset_size in [500, 5000, 50000]:
    train_loader = load_cifar100_subset(subset_size)
    print(f"Pretraining on {subset_size} samples of CIFAR-100")
    pretrain_on_cifar100(pretrain_model, train_loader, subset_size, pretrain_optimizer, criterion, device)

train_dataset = CIFAR10(root='./data', train=True, download=True, transform=transform)
optimizer = optim.Adam(pretrain_model.parameters(), lr=1e-4, weight_decay=1e-5)

subset_size = 500
subset_indices = torch.randperm(len(train_dataset))[:subset_size]
train_subset = Subset(train_dataset, subset_indices)
train_loader = DataLoader(train_subset, batch_size=128, shuffle=True, num_workers=2)

# Fine-tune on CIFAR-10 after pretraining
fine_tune_model = VisionTransformer(img_size=224, patch_size=16, in_channels=3, num_classes=10, embed_dim=256, depth=3, num_heads=8, mlp_dim=1024).to(device)
fine_tune_optimizer = optim.Adam(fine_tune_model.parameters(), lr=1e-4, weight_decay=1e-5)

# Load the pretrained model (ignoring classifier layer)
for subset_size in [500]:
  fine_tune_model, optimizer, start_epoch = load_checkpoint_ignore_classifier(fine_tune_model, optimizer, f"{checkpoint_dir}/cifar100/subset_{subset_size}/vit_cifar100_subset_{subset_size}_epoch_100.pth")

  # Fine-tune the model on CIFAR-10
  fine_tune_on_cifar10(fine_tune_model, train_loader, fine_tune_optimizer, criterion, device, subset_size)

  # train_with_early_stopping(fine_tune_model, train_loader, val_loader, optimizer, criterion, device)

def evaluate_on_cifar10(model, test_loader, criterion, device, writer=None, epoch=None):
    model.eval()  # Set model to evaluation mode
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for inputs, targets in tqdm(test_loader, desc="Evaluating", unit="batch"):
            inputs, targets = inputs.to(device), targets.to(device)

            # Forward pass
            outputs = model(inputs)
            loss = criterion(outputs, targets)

            # Update loss and accuracy
            running_loss += loss.item()

            # Calculate number of correct predictions
            _, predicted = torch.max(outputs, 1)
            correct += (predicted == targets).sum().item()
            total += targets.size(0)

            if writer is not None and epoch is not None:
              writer.add_scalar('Correct/Total', correct, total)

    avg_loss = running_loss / len(test_loader)
    accuracy = 100 * correct / total

    return avg_loss, accuracy

# Load CIFAR-10 test dataset
test_dataset = CIFAR10(root='./data', train=False, download=True, transform=transform)

# Create DataLoader for test set
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=2)

# Initialize Vision Transformer model for CIFAR-10
model = VisionTransformer(img_size=224, patch_size=16, in_channels=3, num_classes=10, embed_dim=256, depth=3, num_heads=8, mlp_dim=1024).to(device)

subset_size = 500
# Load model checkpoint
model, optimizer, start_epoch = load_checkpoint(model, optimizer, f"{checkpoint_dir}/cifar10/subset_{subset_size}/vit_cifar10_subset_{subset_size}_epoch_10.pth")
#model, optimizer, start_epoch = load_checkpoint_ignore_classifier(model, optimizer, f"{checkpoint_dir}/cifar100/subset_{subset_size}/vit_cifar100_subset_{subset_size}_epoch_10.pth")

# Define loss function
criterion = nn.CrossEntropyLoss()

# Evaluate model on CIFAR-10 test set
test_loss, test_accuracy = evaluate_on_cifar10(model, test_loader, criterion, device, writer_testing, 10)
print(f"Checkpoint: cifar10 subset size:{subset_size}, epoch: 10")
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.2f}%")

def fine_tune_resnet(train_loader, optimizer, criterion, device, num_epochs=10):
    resnet_model.train()
    for epoch in range(num_epochs):
        running_loss = 0.0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = resnet_model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"ResNet Epoch {epoch+1}, Loss: {running_loss / len(train_loader):.4f}")

def evaluate_models(test_loader, criterion, device):
    models = {'VisionTransformer': model, 'ResNet': resnet_model}
    for model_name, model in models.items():
        model.eval()
        correct, total, running_loss = 0, 0, 0.0
        with torch.no_grad():
            for inputs, targets in test_loader:
                inputs, targets = inputs.to(device), targets.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                running_loss += loss.item()
                _, predicted = torch.max(outputs, 1)
                correct += (predicted == targets).sum().item()
                total += targets.size(0)
        accuracy = 100 * correct / total
        avg_loss = running_loss / len(test_loader)
        print(f"{model_name} - Test Loss: {avg_loss:.4f}, Test Accuracy: {accuracy:.2f}%")

# Initialize the ResNet model for CIFAR-10
resnet_model = resnet18(pretrained=False)  # Use pretrained=True for transfer learning
resnet_model.fc = nn.Linear(resnet_model.fc.in_features, 10)  # Adjust output layer for CIFAR-10 (10 classes)
resnet_model = resnet_model.to(device)

# Define separate optimizers for each model
resnet_optimizer = optim.Adam(resnet_model.parameters(), lr=1e-4, weight_decay=1e-5)

fine_tune_resnet(train_loader, resnet_optimizer, criterion, device, num_epochs=10)

evaluate_models(test_loader, criterion, device)

# Commented out IPython magic to ensure Python compatibility.
#Tensorboard
# %load_ext tensorboard
# %tensorboard --logdir=runs